### ISSUE TITLE
Task Sequence Failure at Script Step

### ISSUE THREAD

**Issue by jdecookecs** [MSEndpointMgr/ConfigMgr#228]
I got everything setup following the steps provided.  I verified that the Web Service connects and finds my packages using DAT.  I made sure the packages are distributed.  I checked my parameters on the script task sequence step.  The error I'm getting seems to reference something wrong with the boot disk or partition format but that doesn't really make sense since my task sequence works just fine without the driver automation steps.  Any help would be greatly appreciated.

![IMG_20200507_085012_2](https://user-images.githubusercontent.com/64022167/81304201-bfea3b80-904a-11ea-8107-bf21eb809362.jpg)
![MDM_TS](https://user-images.githubusercontent.com/64022167/81304225-c678b300-904a-11ea-9567-311731dc84f5.jpg)

**Comment by NickolajA** [comment]
Please attach the ApplyDriverPackage.log file, otherwise it's hard to know what happened.

**Comment by jdecookecs** [comment]
I don't think the log is even being created.  I think it's failing to run my package at that point in the task sequence.  If I place the step after the "Setup Windows and ConfigMgr" step then it actually runs the script, but get errors, so I don't think there is a problem with my package.  I'm assuming placing it after that step causing problem since the instructions say to NOT have it run in full OS.

**Comment by jdecookecs** [comment]
I figured out my problem.  I didn't know you had to enable Powershell components in the boot image in order for scripts to work in WinPE.  Everything worked correctly.  Thanks!!
