### ISSUE TITLE
Driver match failing

### ISSUE THREAD

**Issue by areskot** [MSEndpointMgr/ConfigMgr#240]
Script version 3.0.4, Webservice version 1.8.0, MECM 2002, Win10 1909 x64.
Invoke-CMApplyDriverPackage.ps1 keeps failing on HP models, the "ApplyDriverpackage.log" gives me 
the following error: 

"Skipping driver package since only 3/4 checks was matched"

This goes for all my HP models in production, any suggestions?

**Comment by Mrgreen17** [comment]
I'm having the same issue, 3/4 checks was a matched. using Script version 3.0.5, Webservice version 1.8.0, MECM 2002, Win10 1909 x64.

**Comment by Mrgreen17** [comment]
Just letting you know it worked when I added -Targetosversion "18363"

**Comment by areskot** [comment]
-Targetosversion "18363" worked like a charm for my HP's, but my older Lenovos failed. -OSVersionFallback solved it for my Lenovos.
