### ISSUE TITLE
unhandled exit code: -2147221246

### ISSUE THREAD

**Issue by m0nkiwitacaus** [MSEndpointMgr/ConfigMgr#256]
First: Thank you for all the work you've done. This has saved us TONS of time with Bare metal imaging.

Hope this is a quick answer and maybe I'm overlooking something. Would you expect either the "OSUpgrade" or the "PreCache" options to work for a machine that's talking to our CMG? 

I am running the Invoke-CMApplyDriverPackage.ps1 w/ the Bypass policy, and the Parameter is marked as the following, but I've tried both OSUpgrade and PreCache:
-URI "http://FQDN.company.com/ConfigMgrWebService/ConfigMgr.asmx" -SecretKey "<SecretKey>" -Filter "Drivers" -DeploymentType "OSUpgrade"

Our clients are able to receive policies from our MP to talk to the CMG either when outside the network or on VPN. The Web Service is installed on our MP, and all driver packages have been distributed to the CMG. I've tried re-distributing one of the drivers I'm testing from home, but keep coming across this error in the ApplyDriverPackage.log (attached).
 - Driver package content download process returned an unhandled exit code: -2147221246

Though I'm able to make a connection to the webservice, and it successfully queries all models before coming across the right identity. It then attempts to download it, and we're greeted with this:
  - Attempting to download content files for matched driver package: Drivers - Dell Latitude 5401 - Windows 10 x64
 - Setting task sequence variable OSDDownloadDownloadPackages to: <site_code>00268
 - Setting task sequence variable OSDDownloadDestinationLocationType to: Custom	ApplyDriverPackage
 - Setting task sequence variable OSDDownloadDestinationVariable to: OSDDriverPackage
 - Setting task sequence variable OSDDownloadDestinationPath to: %_SMSTSMDataPath%\DriverPackage
 - Starting package content download process (FullOS), this might take some time
 - Driver package content download process returned an unhandled exit code: -2147221246
 - [ApplyDriverPackage]: Apply Driver Package process failed, please refer to previous error or warning messages
[ApplyDriverPackage.txt](https://github.com/MSEndpointMgr/ConfigMgr/files/5013329/ApplyDriverPackage.txt)

Thank you for any pointers

**Comment by NickolajA** [comment]
CMG support is something we're aiming for, but unfortunately ConfigMgr doesn't support dynamic package download natively (we've been according to Microsoft themselves, using an unsupported method of downloading the content itself by simply calling the executable responsible). It's definitely on our roadmap, but we're kind of dependent on Microsoft at this point.

**Comment by m0nkiwitacaus** [comment]
Thank you @NickolajA for the response. 

It looks like there might be even some bugs Microsoft is having when calling a "Download package content" when running a precache task if a device is on the internet (from some reddit pages, it sounds like a few have opened up cases). 

I'm sure all of us are looking forward to more updates from your group in the future. Thanks again for your brilliant efforts, tools, and documentation.

**Comment by NickolajA** [comment]
Let me just add to this. There's some really good news coming very soon. Stay tuned.
