### ISSUE TITLE
OS version important or not?

### ISSUE THREAD

**Issue by kingskawn** [MSEndpointMgr/ConfigMgr#258]
We have W10 1803 and I downloaded the driver packs for our HP models for 1803. We now are updating OS to 1909 and I'm wondering if the driver pack and OS for which has been downloaded is important? When I look at the ApplyDriverPackage.log I can see that it looks for the model SKU value but also OS version. Does it mean I have to redownload all driver packs for all 1909 version or will it install what there is available ?
For now it errors out with "Process completed with exit code 21" in the SMSTS.log

I'm using version 2.2.6 with webservice 1.60

`
Attempting to   find a match for driver package: Drivers - Hewlett-Packard EliteBook 850 G5   Notebook PC - Windows 10 10.0.17134.1 x64 (PRT0043A) | ApplyDriverPackage | 05/08/2020 12:47 | 2580 (0x0A14)
-- | -- | -- | --
Match found for computer model using   detection method: SystemSKU and SKU value (83B2) | ApplyDriverPackage | 05/08/2020 12:47 | 2580 (0x0A14)
Unable to match driver package name with   OS version '1903', falling back to match found for 'Windows 10' | ApplyDriverPackage | 05/08/2020 12:47 | 2580 (0x0A14)
Match found for manufacturer, operating   system and architecture: Drivers - Hewlett-Packard EliteBook 850 G5 Notebook   PC - Windows 10 10.0.17134.1 x64 (PRT0043A) | ApplyDriverPackage | 05/08/2020 12:47 | 2580 (0x0A14)
Adding driver package to list of packages   to process | ApplyDriverPackage | 05/08/2020 12:47 | 2580 (0x0A14)
Attempting to find a match for driver   package: Drivers - Hewlett-Packard Pro x2 612 G2 Tablet Base Model - Windows   10 10.0.17134.1 x64 (PRT0047A) | ApplyDriverPackage | 05/08/2020 12:47 | 2580 (0x0A14)
Unable to match computer model   using detection method: SystemSKU (83B2) | ApplyDriverPackage | 05/08/2020 12:47 | 2580 (0x0A14)
Driver package does not meet   computer model, manufacturer and operating system and architecture criteria:   Drivers - Hewlett-Packard Pro x2 612 G2 Tablet Base Model - Windows 10   10.0.17134.1 x64 (PRT0047A) | ApplyDriverPackage | 05/08/2020 12:47 | 2580 (0x0A14)
Attempting to find a match for driver   package: Drivers - Hewlett-Packard EliteBook 840 G5 Notebook PC - Windows 10   1803 x64 (PRT0049E) | ApplyDriverPackage | 05/08/2020 12:47 | 2580 (0x0A14)
Match found for computer model using   detection method: SystemSKU and SKU value (83B2) | ApplyDriverPackage | 05/08/2020 12:47 | 2580 (0x0A14)
Unable to match driver package name with   OS version '1903', falling back to match found for 'Windows 10' | ApplyDriverPackage | 05/08/2020 12:47 | 2580 (0x0A14)
Match found for manufacturer, operating   system and architecture: Drivers - Hewlett-Packard EliteBook 840 G5 Notebook   PC - Windows 10 1803 x64 (PRT0049E) | ApplyDriverPackage | 05/08/2020 12:47 | 2580 (0x0A14)
Adding driver package to list of packages   to process | ApplyDriverPackage | 05/08/2020 12:47 | 2580 (0x0A14)
Attempting to find a match for driver   package: Drivers - Hewlett-Packard EliteBook 840 G3 Notebook PC - Windows 10   1803 x64 (PRT0049C) | ApplyDriverPackage | 05/08/2020 12:47 | 2580 (0x0A14)
Driver package list contains 2 matches.   Attempting to remove driver packages that do not match the computer model. | ApplyDriverPackage | 05/08/2020 12:47 | 2580 (0x0A14)
Detected that the following driver   package did not match the computer model: Drivers - Hewlett-Packard EliteBook   850 G5 Notebook PC - Windows 10 10.0.17134.1 x64 | ApplyDriverPackage | 05/08/2020 12:47 | 2580 (0x0A14)
Removing driver package due to   inconsistency between computer model value from WMI 'HP EliteBook 840 G5' and   the translated driver package computer model name 'HP EliteBook 850 G5   Notebook PC' | ApplyDriverPackage | 05/08/2020 12:47 | 2580 (0x0A14)
Driver package list contains multiple   matches, attempting to download driver package content based upon latest   package creation date | ApplyDriverPackage | 05/08/2020 12:47 | 2580 (0x0A14)
Vendor specific matching required before   downloading content. Attempting to match Hewlett-Packard driver package based   on OS build number: 1903 | ApplyDriverPackage | 05/08/2020 12:47 | 2580 (0x0A14)
An error occurred while   selecting manufacturer specific driver packages from list, empty list of   packages detected | ApplyDriverPackage | 05/08/2020 12:47 | 2580 (0x0A14)
`

**Comment by NickolajA** [comment]
I'd suggest that you always make sure that you're using the latest version of the script, please grab the latest ones from below:

- ConfigMgr WebService supported version:
https://github.com/MSEndpointMgr/ModernDriverManagement/blob/master/Invoke-CMApplyDriverPackage_Legacy.ps1

- AdminService supported version:
https://github.com/MSEndpointMgr/ModernDriverManagement/blob/master/Invoke-CMApplyDriverPackage.ps1

To answer your question, yes for HP you need to be specific with the OS version, as HP release different driver packages per Windows 10 build. It's possible that most of the drivers for 1803 will also work with 1909, however it's probably not a "supported" (meaning tested by HP) scenario. So yes again, you'll need to download the driver packages for 1909 as well.

**Comment by kingskawn** [comment]
Thanks Nicolaj, so I need to download all my driver packs again for 1909 OS. That's a lot of disk space ;-) 

I'm using 'legacy' version of the script now but I see in the Invoke-CMApplyDriverPackage.ps1 version 4.0.1 that the use of the webservice is deprecated. In your manual on https://www.msendpointmgr.com/modern-driver-management in the examples everything is configured with the webservice. Does it mean -URI and -SecretKey isn't necessary anymore for future releases ?

**Comment by NickolajA** [comment]
The docs will soon be updated, we're finalizing it all (takes quite a lot of time). Driver Automation Tool can also compress driver packages into 7-zip extractors which will save you disk space.

**Comment by kingskawn** [comment]
Yes, I know for the zipped driver packs but I use the IPU TS from Gary and he uses the extracted packs. If I have time I can maybe instruct the zipped folders to use. Could save me some space but all from 1803 would be deleted in the end :-)

Thanks for all your work ;-)
