### ISSUE TITLE
Error downloading driver package

### ISSUE THREAD

**Issue by korbinianotto** [MSEndpointMgr/ConfigMgr#273]
Hey guys,

can anyone help with the problem in the screenshot?

Thank you!

![image](https://user-images.githubusercontent.com/53822568/94007911-6b99eb00-fda2-11ea-9a82-e007403f8023.png)

**Comment by merlinfrombelgium** [comment]
Hi @korbinianotto,

Error -2147221246 translates to 0x80040102 and is related to Location Requests.
Please check and double check that package OTF0021F has been properly distributed in CM. It might help to check smsts.log as well to see which Distribution Points (if any) were returned for that package.

Good luck and let us know what you find!

**Comment by korbinianotto** [comment]
updating the DP solved the problem. thank you.
