### ISSUE TITLE
Error since switching to the new AdminService

### ISSUE THREAD

**Issue by tcapacci** [MSEndpointMgr/ConfigMgr#308]
Hi,

I have followed the instructions to use the AdminService but I am getting in my TS:
Failed to run the last action: Dynamically Apply Drivers. Result 1. Execution of task sequence failed.	TSManager	3/6/2021 2:03:40 PM	17856 (0x45C0)

The ApplyDriverPackage.log:

[ApplyDriverPackage]: Apply Driver Package process initiated	ApplyDriverPackage	3/6/2021 2:03:35 PM	18868 (0x49B4)
 - Apply driver package deployment type: DriverUpdate	ApplyDriverPackage	3/6/2021 2:03:35 PM	18868 (0x49B4)
 - Apply driver package operational mode: Production	ApplyDriverPackage	3/6/2021 2:03:35 PM	18868 (0x49B4)
[PrerequisiteChecker]: Starting environment prerequisite checker	ApplyDriverPackage	3/6/2021 2:03:35 PM	18868 (0x49B4)
 - Supported computer platform detected, script execution allowed to continue	ApplyDriverPackage	3/6/2021 2:03:35 PM	18868 (0x49B4)
 - Supported operating system version currently running detected, script execution allowed to continue	ApplyDriverPackage	3/6/2021 2:03:35 PM	18868 (0x49B4)
 - Computer manufacturer determined as: Dell	ApplyDriverPackage	3/6/2021 2:03:36 PM	18868 (0x49B4)
 - Computer model determined as: Latitude 7390	ApplyDriverPackage	3/6/2021 2:03:36 PM	18868 (0x49B4)
 - Computer SystemSKU determined as: 081B	ApplyDriverPackage	3/6/2021 2:03:36 PM	18868 (0x49B4)
 - Computer Fallback SystemSKU determined as: 081B	ApplyDriverPackage	3/6/2021 2:03:36 PM	18868 (0x49B4)
 - Computer model detection was successful	ApplyDriverPackage	3/6/2021 2:03:36 PM	18868 (0x49B4)
 - Computer SystemSKU detection was successful	ApplyDriverPackage	3/6/2021 2:03:36 PM	18868 (0x49B4)
 - Computer details successfully verified	ApplyDriverPackage	3/6/2021 2:03:36 PM	18868 (0x49B4)
 - Determined primary computer detection method: SystemSKU	ApplyDriverPackage	3/6/2021 2:03:36 PM	18868 (0x49B4)
[PrerequisiteChecker]: Completed environment prerequisite checker	ApplyDriverPackage	3/6/2021 2:03:36 PM	18868 (0x49B4)
[AdminService]: Starting AdminService endpoint phase	ApplyDriverPackage	3/6/2021 2:03:36 PM	18868 (0x49B4)
 - Attempting to determine AdminService endpoint type based on current active Management Point candidates and from ClientInfo class	ApplyDriverPackage	3/6/2021 2:03:36 PM	18868 (0x49B4)
 - Determined AdminService endpoint type as: Internal	ApplyDriverPackage	3/6/2021 2:03:36 PM	18868 (0x49B4)
 - Successfully read service account user name from TS environment variable 'MDMUserName': a*m*n*s*r*i*e*s*c*@*o*p*r*m*r*g*o*p*l*c*l	ApplyDriverPackage	3/6/2021 2:03:36 PM	18868 (0x49B4)
 - Successfully read service account password from TS environment variable 'MDMPassword': ********	ApplyDriverPackage	3/6/2021 2:03:36 PM	18868 (0x49B4)
 - Setting 'AdminServiceURL' variable to: https://sccm01.corp.acme.local/AdminService/wmi	ApplyDriverPackage	3/6/2021 2:03:36 PM	18868 (0x49B4)
[AdminService]: Completed AdminService endpoint phase	ApplyDriverPackage	3/6/2021 2:03:36 PM	18868 (0x49B4)
[DriverPackage]: Starting driver package retrieval using method: AdminService	ApplyDriverPackage	3/6/2021 2:03:36 PM	18868 (0x49B4)
 - Querying AdminService for driver package instances	ApplyDriverPackage	3/6/2021 2:03:36 PM	18868 (0x49B4)
 - Calling AdminService endpoint with URI: https://sccm01.corp.acme.local/AdminService/wmi/SMS_Package?$filter=contains(Name,'Drivers')	ApplyDriverPackage	3/6/2021 2:03:36 PM	18868 (0x49B4)
 - The remote AdminService endpoint certificate is invalid according to the validation procedure. Error message: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.	ApplyDriverPackage	3/6/2021 2:03:36 PM	18868 (0x49B4)
 - Will attempt to set the current session to ignore self-signed certificates and retry AdminService endpoint connection	ApplyDriverPackage	3/6/2021 2:03:36 PM	18868 (0x49B4)
 - Retrieved a total of '17' driver packages from AdminService matching operational mode: Production	ApplyDriverPackage	3/6/2021 2:03:37 PM	18868 (0x49B4)
[ApplyDriverPackage]: Apply Driver Package process failed, please refer to previous error or warning messages	ApplyDriverPackage	3/6/2021 2:03:39 PM	18868 (0x49B4)

**Comment by aidbish** [comment]
do you have 17 driver packages, mine seems to have 1 more than i have

otherwise i have the same issue

**Comment by tcapacci** [comment]
Yes I do have 17 driver packages

But the logs wont show me what the issue is when trying to upgrade a client

**Comment by aidbish** [comment]
check this post out

https://github.com/MSEndpointMgr/ModernDriverManagement/issues/88
and
https://github.com/MSEndpointMgr/ModernDriverManagement/issues/77

i just updated the script and i can now do inplace upgrade

**Comment by chaosisbliss** [comment]
Do you have PKI setup for your site? I see an error in your logs referring to the cert.

The remote AdminService endpoint certificate is invalid according to the validation procedure. Error message: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel

**Comment by tcapacci** [comment]
Thanks aidbish! I quoted 20H2 in the script and now it runs fine

**Comment by tcapacci** [comment]
> Thanks aidbish! I quoted 20H2 in the script and now it runs fine
