### ISSUE TITLE
Error: Download and package must be different

### ISSUE THREAD

**Issue by AVPRiga** [MSEndpointMgr/ConfigMgr#313]
![image](https://user-images.githubusercontent.com/16636615/113266074-7eefbb00-92dd-11eb-8504-8d05cf9d76c7.png)
Some issue when I  select necessary model windows version and press "Start Download | Extract | Import" 
I receive error "Error: Download and package must be different"

**Comment by Wavee7** [comment]
You need to provide a different path on **Common Settings --> Storage Locations** tab and on **ConfigMgr Settings --> Site Server Settings | Package Options ---> Package Storage Path**

**Comment by AVPRiga** [comment]
@Wavee7 Great! Big thanks to you! Happy Easter!
