### ISSUE TITLE
Detection Method for Surface Book 2 Not matching

### ISSUE THREAD

**Issue by itmmdj** [MSEndpointMgr/ConfigMgr#332]
Here is the ApplyDriverPackage.log

`
[ApplyDriverPackage]: Apply Driver Package process initiated	ApplyDriverPackage	8/23/2021 8:26:36 AM	1796 (0x0704)
 - Apply driver package deployment type: BareMetal	ApplyDriverPackage	8/23/2021 8:26:36 AM	1796 (0x0704)
 - Apply driver package operational mode: Production	ApplyDriverPackage	8/23/2021 8:26:36 AM	1796 (0x0704)
[PrerequisiteChecker]: Starting environment prerequisite checker	ApplyDriverPackage	8/23/2021 8:26:36 AM	1796 (0x0704)
 - Supported computer platform detected, script execution allowed to continue	ApplyDriverPackage	8/23/2021 8:26:36 AM	1796 (0x0704)
 - Computer manufacturer determined as: Microsoft	ApplyDriverPackage	8/23/2021 8:26:36 AM	1796 (0x0704)
 - Computer model determined as: Surface Book 2	ApplyDriverPackage	8/23/2021 8:26:36 AM	1796 (0x0704)
 - Computer SystemSKU determined as: Surface_Book_1832	ApplyDriverPackage	8/23/2021 8:26:36 AM	1796 (0x0704)
 - Computer model detection was successful	ApplyDriverPackage	8/23/2021 8:26:36 AM	1796 (0x0704)
 - Computer SystemSKU detection was successful	ApplyDriverPackage	8/23/2021 8:26:36 AM	1796 (0x0704)
 - Computer details successfully verified	ApplyDriverPackage	8/23/2021 8:26:36 AM	1796 (0x0704)
 - Determined primary computer detection method: SystemSKU	ApplyDriverPackage	8/23/2021 8:26:36 AM	1796 (0x0704)
[PrerequisiteChecker]: Completed environment prerequisite checker	ApplyDriverPackage	8/23/2021 8:26:36 AM	1796 (0x0704)
[AdminService]: Starting AdminService endpoint phase	ApplyDriverPackage	8/23/2021 8:26:36 AM	1796 (0x0704)
 - Detected that script was running within a task sequence in WinPE phase, automatically configuring AdminService endpoint type	ApplyDriverPackage	8/23/2021 8:26:36 AM	1796 (0x0704)
 - Determined AdminService endpoint type as: Internal	ApplyDriverPackage	8/23/2021 8:26:36 AM	1796 (0x0704)
 - Successfully read service account user name from TS environment variable 'MDMUserName': S*C*S*C*-*S@i*t*u*h*o*g	ApplyDriverPackage	8/23/2021 8:26:37 AM	1796 (0x0704)
 - Successfully read service account password from TS environment variable 'MDMPassword': ********	ApplyDriverPackage	8/23/2021 8:26:37 AM	1796 (0x0704)
 - Setting 'AdminServiceURL' variable to: https://itmssccm01.intouch.org/AdminService/wmi	ApplyDriverPackage	8/23/2021 8:26:37 AM	1796 (0x0704)
[AdminService]: Completed AdminService endpoint phase	ApplyDriverPackage	8/23/2021 8:26:37 AM	1796 (0x0704)
[DriverPackage]: Starting driver package retrieval using method: AdminService	ApplyDriverPackage	8/23/2021 8:26:37 AM	1796 (0x0704)
 - Querying AdminService for driver package instances	ApplyDriverPackage	8/23/2021 8:26:37 AM	1796 (0x0704)
 - Calling AdminService endpoint with URI: https://itmssccm01.intouch.org/AdminService/wmi/SMS_Package?$filter=contains(Name,'Drivers')	ApplyDriverPackage	8/23/2021 8:26:37 AM	1796 (0x0704)
 - The remote AdminService endpoint certificate is invalid according to the validation procedure. Error message: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.	ApplyDriverPackage	8/23/2021 8:26:38 AM	1796 (0x0704)
 - Will attempt to set the current session to ignore self-signed certificates and retry AdminService endpoint connection	ApplyDriverPackage	8/23/2021 8:26:38 AM	1796 (0x0704)
 - Retrieved a total of '11' driver packages from AdminService matching operational mode: Production	ApplyDriverPackage	8/23/2021 8:26:40 AM	1796 (0x0704)
 - Target operating system name configured as: Windows 10	ApplyDriverPackage	8/23/2021 8:26:40 AM	1796 (0x0704)
 - Target operating system architecture configured as: x64	ApplyDriverPackage	8/23/2021 8:26:40 AM	1796 (0x0704)
 - Target operating system version configured as: 2004	ApplyDriverPackage	8/23/2021 8:26:40 AM	1796 (0x0704)
[DriverPackage]: Starting driver package matching phase	ApplyDriverPackage	8/23/2021 8:26:40 AM	1796 (0x0704)
 - Initial count of driver packages before starting filtering process: 11	ApplyDriverPackage	8/23/2021 8:26:40 AM	1796 (0x0704)
 - Filtering driver package results to detected computer manufacturer: Microsoft	ApplyDriverPackage	8/23/2021 8:26:40 AM	1796 (0x0704)
 - Count of driver packages after filter processing: 6	ApplyDriverPackage	8/23/2021 8:26:40 AM	1796 (0x0704)
 - Filtering driver package results to only include packages that have details added to the description field	ApplyDriverPackage	8/23/2021 8:26:40 AM	1796 (0x0704)
 - Count of driver packages after filter processing: 6	ApplyDriverPackage	8/23/2021 8:26:40 AM	1796 (0x0704)
[DriverPackage:ITM001A8]: Processing driver package with 4 detection methods: Drivers - Microsoft Surface Book 3 15 - Windows 10 2004 x64	ApplyDriverPackage	8/23/2021 8:26:41 AM	1796 (0x0704)
[DriverPackage:ITM001AF]: Processing driver package with 4 detection methods: Drivers - Microsoft Surface Laptop 3 - Intel 13 - Windows 10 2004 x64	ApplyDriverPackage	8/23/2021 8:26:41 AM	1796 (0x0704)
[DriverPackage:ITM001B3]: Processing driver package with 4 detection methods: Drivers - Microsoft Surface Book 2 13 - Windows 10 2004 x64	ApplyDriverPackage	8/23/2021 8:26:41 AM	1796 (0x0704)
[DriverPackage:ITM001B0]: Processing driver package with 4 detection methods: Drivers - Microsoft Surface Laptop 3 - Intel 15 - Windows 10 2004 x64	ApplyDriverPackage	8/23/2021 8:26:41 AM	1796 (0x0704)
[DriverPackage:ITM001A7]: Processing driver package with 4 detection methods: Drivers - Microsoft Surface Book 3 13 - Windows 10 2004 x64	ApplyDriverPackage	8/23/2021 8:26:41 AM	1796 (0x0704)
[DriverPackage:ITM001A6]: Processing driver package with 4 detection methods: Drivers - Microsoft Surface Book 2 15 - Windows 10 2004 x64	ApplyDriverPackage	8/23/2021 8:26:41 AM	1796 (0x0704)
[DriverPackage]: Completed driver package matching phase	ApplyDriverPackage	8/23/2021 8:26:41 AM	1796 (0x0704)
[DriverPackageValidation]: Starting driver package validation phase	ApplyDriverPackage	8/23/2021 8:26:41 AM	1796 (0x0704)
 - Amount of driver packages detected by validation process: 0	ApplyDriverPackage	8/23/2021 8:26:41 AM	1796 (0x0704)
 - Validation failed with empty list of matched driver packages, script execution will be terminated	ApplyDriverPackage	8/23/2021 8:26:41 AM	1796 (0x0704)
[ApplyDriverPackage]: Apply Driver Package process failed, please refer to previous error or warning messages	ApplyDriverPackage	8/23/2021 8:26:41 AM	1796 (0x0704)
`
It seems that the name is correct. I really don't know what to do here. The script is looking for the package that has Surface Book 2 in the name.

**Comment by Ar5had07** [comment]
I posted the solution here 

https://github.com/MSEndpointMgr/ModernDriverManagement/issues/33#issuecomment-765365849

**Comment by itmmdj** [comment]
Thank you. I am using a Surface Book 2, but your example got me looking deeper into the scirpt and how it looks up the package.

In my original comment on my package was "(Models included:Surface_Book_2_1832)" but it should actually be "(Models included:Surface_Book_1832)" which is in the ApplyDriverPackage.log. Running the script in debug helped to see this. I will say it is nice that being able to change the comments (which in the script is called $DriverPackageItem.Description) can help the script find the package.
