### ISSUE TITLE
Error in Invoke-CMApplyDriverPackage.ps1 multiple line

### ISSUE THREAD

**Issue by esorow** [MSEndpointMgr/ConfigMgr#347]
Hi, 

did you ever seen those errors in the script execution ? (whatever it s running in a ts or not)

script downloaded 2 days ago from here
any idea ?

thankx for your help
BR

**Comment by merlinfrombelgium** [comment]
Hi @esorow 

Based on the error details, your .ps1 is full of html code, which is not right.

My gut feeling says you may have downloaded the script from the github repo in a wrong way. So please make sure you first click on the script, so you see the contents. Then it's important to right-click the `Raw` button at the top right and save that as the .ps1 file. Open it and verify the contents.

Let me share the direct link to the file to make it easier:
https://github.com/MSEndpointMgr/ConfigMgr/raw/master/Operating%20System%20Deployment/Drivers/Invoke-CMApplyDriverPackage.ps1
Notice the _/raw/_ part in the URL.

Try that and let us know how you get on.

**Comment by esorow** [comment]
@merlinfrombelgium 

thank you for your help and advice ( first time I DL a script from here)

I follow the documentation instructions and I get an error but without any helpfull details 

maybe i can get so more help plz ? 

here the ApplyDriverPackage log file : 

![image](https://user-images.githubusercontent.com/99410641/154070927-c80a3a33-8375-47cd-b477-4e4cd04c4333.png)

[ApplyDriverPackage]: Apply Driver Package process failed, please refer to previous error or warning messages --> there is no other error message 

no more informations in the SMSTS.log file except : Failed to run the action: Appliquer les drivers. Error 1

any idea ?

thanks again
BR
Eli

**Comment by merlinfrombelgium** [comment]
Glad you got that far already. Let's figure out the next step.

Can you share with us the script parameters you're using in your task sequence? Make sure to mask any user names and passwords and such.

Have you configured the TS variables MDMUsername and MDMPassword? See step 4 of the documentation https://msendpointmgr.com/modern-driver-management/#setup-required-task-sequence-variables

**Comment by esorow** [comment]
Hello @merlinfrombelgium ,

here are the TS steps
Applied just after network settings and before windows and ccm settings like described in the documentation.

![image](https://user-images.githubusercontent.com/99410641/154228237-3e3c66b4-e262-46e3-a14c-f74e784448fc.png)

no error in smsts.log file for the MdM variables step


![image](https://user-images.githubusercontent.com/99410641/154229521-dab2fc38-2853-4144-a921-3e79a8a9f56d.png)


i must admit, i' stuck with this lack of error informations

thanks again for helping

**Comment by merlinfrombelgium** [comment]
Your screenshots are very helpful. I see you've used MDM_User and MDM_Pwd as variable names. The script will only work with the documented variable names MDMUsername and MDMPassword.

**Comment by merlinfrombelgium** [comment]
Whoops. Sent you the wrong URL earlier. That one is the old repo. Please use this one only:
https://github.com/MSEndpointMgr/ModernDriverManagement/blob/master/Invoke-CMApplyDriverPackage.ps1

**Comment by esorow** [comment]
@merlinfrombelgium 
no worry i use the good one :) (the first gave me lot of error it was an old version)
and thank you again you were right ! i didn't use the same names as in the script.... my mistake !
all works fine now thanks to you.
